import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ShieldCheck, Eye, Lock, FileText, Send } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy — Sarvalay Managed Art Platform',
  description: 'Learn how Sarvalay protects your personal data, artist portfolios, and commercial design concepts.',
};

export default function PrivacyPage() {
  const sections = [
    {
      icon: Eye,
      title: 'Information We Collect',
      desc: 'We collect relevant details necessary to manage art B2B transactions. This includes contact details of B2B clients, project measurements, photos of walls, artist resumes, portfolios, and financial payouts verification. We do not sell or lease this information to third parties.',
    },
    {
      icon: ShieldCheck,
      title: 'How We Protect Your Data',
      desc: 'All project mockups generated by our Intelligent Visual Design Engine (IVDE) are stored securely. Payment card data is processed directly via licensed payment gateways under industry compliance standards. Personal credentials, artist tiers, and contracts are highly protected.',
    },
    {
      icon: Lock,
      title: 'B2B Intellectual Property & Design Rights',
      desc: 'Proprietary designs submitted by verified artists remain protected. We enforce strict non-disclosure agreements across our operations so that commercial concepts under evaluation are never leaked or replicated by competing sites.',
    },
    {
      icon: FileText,
      title: 'Your Rights & Controls',
      desc: 'You can view, edit, or request the deletion of your account and files from our system. If you are an artist, your data is visible to verified corporate accounts looking for art installation but hidden from general public queries to maintain confidentiality.',
    },
  ];

  return (
    <main>
      <Navbar />
      <div style={{ paddingTop: '72px' }}>
        {/* Header */}
        <section style={{ padding: '80px 24px 48px', background: 'rgba(179,18,23,0.03)', borderBottom: '1px solid var(--color-border)', textAlign: 'center' }}>
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <div className="section-label" style={{ justifyContent: 'center', marginBottom: '16px' }}>Trust &amp; Security</div>
            <h1 style={{ fontFamily: 'var(--font-heading)', fontSize: 'clamp(2rem, 4vw, 2.8rem)', fontWeight: '800', color: 'var(--color-text-primary)', marginBottom: '16px' }}>
              Privacy <span className="gradient-text">Policy</span>
            </h1>
            <p style={{ color: 'var(--color-text-secondary)', fontSize: '1rem', lineHeight: '1.6' }}>
              Last updated: May 22, 2026. Sarvalay is committed to safeguarding the data of both our corporate clients and our professional artist network.
            </p>
          </div>
        </section>

        {/* Content */}
        <section style={{ padding: '80px 24px', maxWidth: '1000px', margin: '0 auto' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '28px' }} className="contact-grid">
            {sections.map((sec, idx) => {
              const Icon = sec.icon;
              return (
                <div key={idx} className="glass-card" style={{ padding: '32px', border: '1px solid var(--color-border)', borderRadius: '12px' }}>
                  <div style={{ display: 'flex', gap: '16px', alignItems: 'flex-start' }}>
                    <div style={{ width: '40px', height: '40px', background: 'rgba(179,18,23,0.08)', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--color-indigo)', flexShrink: 0 }}>
                      <Icon size={20} />
                    </div>
                    <div>
                      <h3 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.15rem', fontWeight: '700', color: 'var(--color-text-primary)', marginBottom: '10px' }}>{sec.title}</h3>
                      <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.875rem', lineHeight: '1.7' }}>{sec.desc}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Full Text Notice */}
          <div className="glass-card" style={{ marginTop: '48px', padding: '32px', border: '1px solid var(--color-border)', borderRadius: '12px' }}>
            <h3 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.25rem', fontWeight: '700', color: 'var(--color-text-primary)', marginBottom: '16px' }}>Detailed Operational Data Usage</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', color: 'var(--color-text-secondary)', fontSize: '0.875rem', lineHeight: '1.7' }}>
              <p>
                <strong>1. Cookies and Analytics:</strong> We use essential analytical cookies to monitor loading speed and dashboard activity. This helps us ensure that the IVDE engine operates efficiently and renders mockups instantly. No third-party marketing cookies are loaded.
              </p>
              <p>
                <strong>2. Third-Party Integrations:</strong> Sarvalay integrates with secure payment systems (Razorpay/Stripe) and cloud servers to host artist portfolios. We share strictly necessary data with these platforms to perform checkout operations and deliver reliable cloud services.
              </p>
              <p>
                <strong>3. Regulatory Compliance:</strong> In cases where it is requested by government authorities under standard legal mandates in India, we may share minimal required project information in strict compliance with the local law.
              </p>
            </div>
          </div>

          {/* Contact Support block */}
          <div style={{ marginTop: '56px', textAlign: 'center', padding: '40px 24px', background: 'rgba(179,18,23,0.05)', borderRadius: '16px', border: '1px solid var(--color-border)' }}>
            <h3 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.3rem', fontWeight: '700', color: 'var(--color-text-primary)', marginBottom: '8px' }}>Have questions about your privacy?</h3>
            <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.9rem', marginBottom: '24px', maxWidth: '480px', margin: '0 auto 24px' }}>
              Reach out to our security &amp; operations desk. We respond to data privacy inquiries within 24 working hours.
            </p>
            <Link href="/contact" className="btn-primary" style={{ display: 'inline-flex', gap: '8px' }}>
              <span>Contact Privacy Officer</span>
              <Send size={14} />
            </Link>
          </div>
        </section>
      </div>
      <Footer />
    </main>
  );
}
